---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- networkpolicy.yaml

# patches:
# - patch: |-
#     apiVersion: apps/v1
#     kind: Deployment
#     metadata:
#       name: replaceme
#     spec:
#       template:
#         spec:
#           containers:
#             - name: main
#               env:
#               - name: LOG_LEVEL
#                 value: "INFO"