---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: replaceme
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: replaceme
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}