---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-production
  labels:
    app.kubernetes.io/managed-by: argocd-applicationset
    app.kubernetes.io/part-of: argocd-applicationset
spec:
  generators:
  - matrix: 
      generators:
        - list:
            elements:
            - clusterAddress: https://kubernetes.default.svc
              clusterNamespace: default
              stageName: production
            - clusterAddress: https://kubernetes.default.svc
              clusterNamespace: default
              stageName: staging
        - git:
            repoURL: https://github.com/thomasklinger1234/klusterinfra.git
            revision: HEAD
            directories:
            - path: kustomizations/*
  template:
    metadata:
      name: "kustomizations-{{ path.basename }}-{{ stageName }}"
      labels:
        app.kubernetes.io/managed-by: argocd-applicationset
        app.kubernetes.io/part-of: argocd-applicationset
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      annotations:
        notifications.argoproj.io/subscribe.on-sync-failed.teams: default
        notifications.argoproj.io/subscribe.on-health-degraded.teams: default
    spec:
      project: default
      source:
        repoURL: "https://github.com/thomasklinger1234/klusterinfra"
        targetRevision: HEAD
        path: "{{ path }}/overlays/{{ stageName }}"
      destination:
        server: "{{ clusterAddress }}"
        namespace: '{{ clusterNamespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true

