name: charts_ci

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
    paths:
      - "charts/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "charts/**"

env: {}

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
        with:
          version: v3.10.2
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Helm Lint
        run: |
          HELM_CHARTS="$(ls -d charts/*)"
          HELM_LINT_OPTS=""

          for chart in ${HELM_CHARTS}; do
            helm dependency build ${chart}
            helm lint ${chart} ${HELM_LINT_OPTIONS}
          done
