---
name: ci

on:
  workflow_dispatch:
    inputs: {}
  pull_request_target:
    types: [ labeled, opened, synchronize, reopened, auto_merge_enabled ]
  push:
    branches:
      - main
    paths:
      - "kustomizations/**"

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    env: {}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      # Kubernetes Manifests
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
      - name: Kustomizations
        run: |
          kubectl kustomize kustomizations/template/overlays/staging
          kubectl kustomize kustomizations/template/overlays/production

      # Release
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        if: github.ref == 'refs/heads/main'
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          changelog_increment_filename: body.md
          no_raise: "3,16,21"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          body_path: "body.md"
          tag_name: "${{ env.REVISION }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"